lynko/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import signup, checkout
from .forms import LoginForm

app_name='accounts'

urlpatterns = [
    path('checkout/',checkout, name='checkout'),
    path('signup/', signup, name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html',form_class=LoginForm),name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

lynko/core/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import *

app_name='core'

urlpatterns = [
    path('', login_required(index), name='index'),
    path('about/', about, name='about'),
    path('pricing/', pricing, name='pricing'),
]

lynko/dashboard/urls.py
from django.urls import path

from .views import *


app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard'),
]

lynko/link/urls.py
from django.urls import path

from .views import *

app_name = 'link'

urlpatterns =[
    path('create-category/', create_category, name='create_category'),
    path('create-link/', create_link, name='create_link'),
    path('<int:pk>/edit/', edit_link, name='edit'),
    path('<int:pk>/delete/', delete_link, name='delete'),
    path('categories/<int:pk>/edit/', edit_category, name='edit_category'),
    path('categories/<int:pk>/delete/', delete_category, name='delete_category'),
   
]

lynko/lynko/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('',include('core.urls')),
    path('account/',include('accounts.urls')),
    path('links/',include('link.urls')),
    path('dashboard/',include('dashboard.urls')),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
]

lynko/core/models.py
from django.db import models

# Create your models here.

lynko/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

def pricing(request):
    return render(request, 'core/pricing.html')

lynko/core/templates/core/partials/footer.html
<footer class="bg-gray-900 p-6">
    <p class="text-xs text-gray-400">&copy;Pravin kamble 2023</p>
</footer>

lynko/core/templates/core/partials/nav.html
<nav class=" flex items-center justify-between p-6 bg-gray-800">
    <a href="/" class="text-2xl text-cyan-500">Lynko</a>
    <div>
        {% if request.user.is_authenticated %}
            <h2 class="text-xl text-white font-serif">Account: {{ request.user.username }}</h2>
        {% endif %}
    </div>
    <div class="space-x-4">
        <a href="{% url 'core:about' %}" class="text-white ">About</a>
        <a href="{% url 'core:pricing' %}" class="text-white ">Pricing</a>
        
        {% if request.user.is_authenticated %}
            <a href="{% url 'link:create_category' %}" class="py-2 px-4 bg-cyan-600 text-white rounded-xl ">Create Category</a>
            <a href="{% url 'link:create_link' %}" class="py-2 px-4 bg-cyan-600 text-white rounded-xl ">Create link</a>
            <a href="{% url 'dashboard:dashboard' %}" class="py-2 px-4 bg-cyan-600 text-white rounded-xl ">My Dashboard</a>
            <a href="{% url 'accounts:logout' %}" class="py-2 px-4 bg-rose-600 text-white rounded-xl ">Logout</a>
        {% else %}
            <a href="{% url 'accounts:signup' %}" class="py-4 px-4 bg-cyan-600 text-white rounded-xl ">Sign up</a>
            <a href="{% url 'accounts:login' %}" class="py-4 px-4 bg-gray-600 text-white rounded-xl ">Log in</a>
        {% endif %}
    </div>
</nav>