lynko/core/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import *

app_name='core'

urlpatterns = [
    path('', login_required(index), name='index'),
    path('about/', about, name='about'),
    path('pricing/', pricing, name='pricing'),
]

lynko/dashboard/urls.py
from django.urls import path

from .views import *


app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard'),
]

lynko/link/urls.py
from django.urls import path

from .views import *

app_name = 'link'

urlpatterns =[
    path('create-category/', create_category, name='create_category'),
    path('create-link/', create_link, name='create_link'),
    path('<int:pk>/edit/', edit_link, name='edit'),
    path('<int:pk>/delete/', delete_link, name='delete'),
    path('categories/<int:pk>/edit/', edit_category, name='edit_category'),
    path('categories/<int:pk>/delete/', delete_category, name='delete_category'),
   
]

lynko/lynko/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('',include('core.urls')),
    path('account/',include('accounts.urls')),
    path('links/',include('link.urls')),
    path('dashboard/',include('dashboard.urls')),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
]

lynko/dashboard/models.py
from django.db import models

# Create your models here.

lynko/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


from link.models import Category, Link

@login_required
def dashboard(request):
    categories = Category.objects.filter(created_by=request.user)
    links = Link.objects.filter(created_by=request.user)
    return render(request, 'dashboard/dashboard.html', {'categories': categories, 'links': links})

lynko/dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h2 class="text-2xl font-bold mb-4">My Dashboard</h2>

    <div class="flex flex-col md:flex-row">
        <div class="md:w-1/3 pr-8">
            <h3 class="text-lg font-bold mb-2">Categories</h3>
            <ul>
                {% for category in categories %}
                    <li class="mb-2">
                        <a href="#" class="text-blue-500 hover:underline">{{ category.name }}</a>
                    </li>
                    <div class="space-x-4">
                        <a href="{% url 'link:edit_category' category.pk %}" class="text-sm text-teal-500 hover:text-teal-700">edit</a>
                        <a href="{% url 'link:delete_category' category.pk %}" class="text-sm text-rose-500 hover:text-rose-700">delete</a>
                    </div>
                {% empty %}
                    <li>No categories found.</li>
                {% endfor %}
            </ul>
        </div>

        <div class="md:w-2/3">
            <h3 class="text-lg font-bold mb-2">Links</h3>
            <ul>
                {% for link in links %}
                    <li class="mb-4">
                        <div class="bg-gray-100 px-4 py-2 rounded-lg">
                            <div class="text-lg font-bold mb-2">{{ link.name }}</div>
                            {% if link.description %}
                                <div class="text-gray-700">{{ link.description }}</div>
                            {% endif %}
                            <div class="mt-2 space-x-4">
                                <a href="{{ link.url }}" class="text-blue-500 hover:underline">Open link</a>
                                
                                <a href="{% url 'link:edit' link.pk %}" class="text-sm text-teal-500 hover:text-teal-700">edit</a>
                                
                                <a href="{% url 'link:delete' link.pk %}" class="text-sm text-rose-500 hover:text-rose-700">delete</a>
                            </div>
                        </div>
                    </li>
                {% empty %}
                    <li>No links found.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}